version: '3'
services:
  wildfly:
    build: .
    ports:
      - "8080:8080"  # Application port
      - "9990:9990"  # Management port
    environment:
      - JAVA_OPTS=-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true
    networks:
      - prover-network

networks:
  prover-network:
    driver: bridge
    enable_ipv6: false 