version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: prover
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - prover-network

  wildfly:
    build: .
    ports:
      - "8080:8080"  # Application port
      - "9990:9990"  # Management port
    environment:
      - JAVA_OPTS=-Djava.net.preferIPv4Stack=true -Djboss.bind.address=0.0.0.0 -Djboss.bind.address.management=0.0.0.0
    depends_on:
      - postgres
    networks:
      - prover-network

networks:
  prover-network:
    driver: bridge 